# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_Rd1VzLY05BceOlSJ4F--VgSPu8DN1O
"""
# @title
# ======================================================================
# EJERCICIO 2: SUBIR ESCALERAS CON PROGRAMACIÓN DINÁMICA
# ======================================================================

def formas_de_subir(n, mostrar_proceso=False):
    """
    Calcula la cantidad de formas de subir n escalones
    avanzando 1 o 2 escalones por vez.

    Parámetros:
        n: número de escalones.
        mostrar_proceso: muestra el proceso de cálculo.

    Retorna:
        int: cantidad de formas posibles.
    """

    # Casos base
    if n == 0:
        return 1
    if n == 1:
        return 1

    # Tabla de Programación Dinámica
    tabla = [0] * (n + 1)
    tabla[0] = 1
    tabla[1] = 1

    if mostrar_proceso:
        print("\n PROCESO DE CÁLCULO")
        print("-" * 50)
        print("formas(0) = 1")
        print("formas(1) = 1")

    # Proceso Bottom-Up
    for i in range(2, n + 1):

        # Relación de recurrencia: formas(i) = formas(i-1) + formas(i-2)
        tabla[i] = tabla[i - 1] + tabla[i - 2]

        if mostrar_proceso:
            print(
                f"formas({i}) = formas({i-1}) + formas({i-2}) = "
                f"{tabla[i-1]} + {tabla[i-2]} = {tabla[i]}"
            )

    if mostrar_proceso:
        print("-" * 50)

    return tabla[n]


def generar_combinaciones(n):
    """
    Genera todas las combinaciones posibles para n escalones.
    """

    combinaciones = []

    def backtracking(restante, camino):

        if restante == 0:
            combinaciones.append(camino.copy())
            return

        if restante >= 1:
            camino.append(1)
            backtracking(restante - 1, camino)
            camino.pop()

        if restante >= 2:
            camino.append(2)
            backtracking(restante - 2, camino)
            camino.pop()

    backtracking(n, [])

    return combinaciones


def generar_secuencia(n):
    """
    Genera la secuencia completa de formas desde 0 hasta n.
    """

    if n == 0:
        return [1]

    tabla = [0] * (n + 1)
    tabla[0] = 1
    tabla[1] = 1

    for i in range(2, n + 1):
        tabla[i] = tabla[i - 1] + tabla[i - 2]

    return tabla


# ======================================================================
# PROGRAMA PRINCIPAL
# ======================================================================

def main():

    print("=" * 60)
    print(" 🪜 SUBIR ESCALERAS - PROGRAMACIÓN DINÁMICA")
    print("=" * 60)

    try:

        n = int(input("\n Ingrese el número de escalones: "))

        if n < 0:
            print("\n Error: n debe ser un entero no negativo.")
            return

        print(f"\n Calculando formas de subir {n} escalones...")
        print("=" * 60)

        resultado = formas_de_subir(n, mostrar_proceso=True)

        print("\n RESULTADO FINAL:")
        print(f"Existen {resultado} formas distintas de subir {n} escalones.")

        # Mostrar combinaciones para valores pequeños
        if n <= 8:

            print("\n Combinaciones posibles:")

            combinaciones = generar_combinaciones(n)

            for i, combo in enumerate(combinaciones, 1):
                pasos = " → ".join(map(str, combo))
                print(f"{i:2}. [{pasos}]")
        else:

              print("\n Hay demasiadas combinaciones para mostrarlas.")

        # Mostrar secuencia completa
        secuencia = generar_secuencia(n)

        print("\n Secuencia de formas:")
        print("n:      ", end="")
        print("  ".join(str(i) for i in range(n + 1)))

        print("formas: ", end="")
        print("  ".join(map(str, secuencia)))

        print(f"\n Relación: formas({n}) = Fibonacci({n + 1})")


    except ValueError:
        print("\n Error: Debe ingresar un número entero válido.")


# Punto de entrada
if __name__ == "__main__":
    main()

