# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vqwBF9LKcJUHfcG-7K4MhklCGr-cCbv
"""

# @title
# ======================================================================
# EJERCICIO 1: SERIE DE FIBONACCI
# ======================================================================

def fibonacci_dp(n, mostrar_proceso=False):
    """
    Calcula el término n de la serie de Fibonacci usando PD.

    Parámetros:
        n (int): Posición del término deseado
        mostrar_proceso (bool): Si True, muestra el proceso de cálculo

    Retorna:
        int: El valor del término n de Fibonacci
    """

    # === CASOS BASE ===
    if n == 0:
        return 0
    elif n == 1:
        return 1

    # === CREACIÓN DE LA TABLA ===
    tabla = [0] * (n + 1)
    tabla[0] = 0
    tabla[1] = 1

    # === PROCESO ITERATIVO ===
    if mostrar_proceso:
        print("\n PROCESO DE CÁLCULO:")
        print("-" * 50)
        print(f"F(0) = 0")
        print(f"F(1) = 1")

    for i in range(2, n + 1):
        tabla[i] = tabla[i - 1] + tabla[i - 2]
        if mostrar_proceso:
            print(f"F({i}) = {tabla[i-1]} + {tabla[i-2]} = {tabla[i]}")

    if mostrar_proceso:
        print("-" * 50)

    return tabla[n]


def obtener_serie_completa(n):
    """
    Obtiene la serie completa de Fibonacci hasta n
    SIN mostrar el proceso de cálculo (solo el resultado).
    """
    serie = []
    for i in range(n + 1):
        # Llamamos SIN mostrar proceso para evitar salidas duplicadas
        serie.append(str(fibonacci_dp(i, mostrar_proceso=False)))
    return serie


# ======================================================================
# PROGRAMA PRINCIPAL
# ======================================================================

def main():
    print("=" * 60)
    print("  SERIE DE FIBONACCI - PROGRAMACIÓN DINÁMICA")
    print("=" * 60)

    try:
        # Solicitar el número n
        n = int(input("\n Ingrese el valor de n: "))

        if n < 0:
            print("\n Error: n debe ser >= 0")
            return

        print(f"\n Calculando Fibonacci({n})...")
        print("=" * 60)

        # === MOSTRAMOS EL PROCESO UNA SOLA VEZ ===
        # Calculamos el resultado mostrando el proceso
        resultado = fibonacci_dp(n, mostrar_proceso=True)

        # === MOSTRAMOS EL RESULTADO FINAL ===
        print(f"\n RESULTADO FINAL:")
        print(f"   F({n}) = {resultado}")

        # === MOSTRAMOS LA SERIE COMPLETA ===
        # Obtenemos la serie SIN mostrar el proceso nuevamente
        serie = obtener_serie_completa(n)
        print(f"\n Serie completa:")
        print(f"   {' → '.join(serie)}")


    except ValueError:
        print("\n Error: Ingrese un número entero válido.")


# Punto de entrada
if __name__ == "__main__":
    main()

# ======================================================================
# EJERCICIO 1: SERIE DE FIBONACCI CON PROGRAMACIÓN DINÁMICA
# ======================================================================

def fibonacci_dp(n, mostrar_proceso=False):
    """
    Calcula Fibonacci(n) mediante Programación Dinámica Bottom-Up.

  Parámetros:
    n (int): término a calcular.
    mostrar_proceso (bool): muestra el cálculo paso a paso.

Retorna:
    tuple: (tabla, resultado)
    """

    # Casos base
    if n == 0:
        return [0], 0

    if n == 1:
        return [0, 1], 1

    # Tabla de programación dinámica
    tabla = [0] * (n + 1)
    tabla[0] = 0
    tabla[1] = 1

    if mostrar_proceso:
        print("\n PROCESO DE CÁLCULO")
        print("-" * 50)
        print("F(0) = 0")
        print("F(1) = 1")

    # Bottom-Up
    for i in range(2, n + 1):

        tabla[i] = tabla[i - 1] + tabla[i - 2]

        if mostrar_proceso:
            print(
                f"F({i}) = F({i-1}) + F({i-2}) = "
                f"{tabla[i-1]} + {tabla[i-2]} = {tabla[i]}"
            )

    if mostrar_proceso:
        print("-" * 50)

    return tabla, tabla[n]


# ======================================================================
# PROGRAMA PRINCIPAL
# ======================================================================

def main():

    print("=" * 60)
    print("    SERIE DE FIBONACCI - PROGRAMACIÓN DINÁMICA")
    print("=" * 60)

    try:

        n = int(input("\n Ingrese el valor de n: "))

        if n < 0:
            print("\n Error: n debe ser un entero no negativo.")
            return

        print(f"\n Calculando Fibonacci({n})...")
        print("=" * 60)

        # Una sola llamada
        tabla, resultado = fibonacci_dp(n, mostrar_proceso=True)

        # Resultado final
        print("\n RESULTADO FINAL:")
        print(f"   F({n}) = {resultado}")

        # Serie completa
        print("\n Serie completa:")
        print("   " + " → ".join(map(str, tabla)))


    except ValueError:
        print("\n Error: Debe ingresar un número entero válido.")


# Punto de entrada
if __name__ == "__main__":
    main()